version: "3"

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www:delegated
    environment:
      PHP_IDE_CONFIG: "serverName=framework.local"
  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www:delegated
